# SETUP
baseurl = "/"
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy"] # disable hugo's content that we don't need...

title = "ByteBitLabs | Limitless thinking" # page title -> see ./layouts/partials/head.html

googleAnalytics = "" # if needed...

[author]
    name = "bytebitlabs.com"
    email = "hello@bytebitlabs.com"

[params]
    description = "Limitless thinking with ByteBitLabs. We do Web3, AI, Cloud, Data and many more IT solutions." # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

# these items will be rendered 1. into a tooltip in the navbar and 2. into the footer - consider that there's limited space when adding more items -> see ./layouts/partials
[[params.social]]
    title = "Email"
    url = "mailto://hello@bytebitlabs.com"
[[params.social]]
    title = "LinkedIn"
    url = "https://linkedin.com/company/bytebitlabs"